language: python
python:
  - "2.7"
service:
  - mongodb
  - elasticsearch
  - redis-server
before_install:
  - mysql -e 'create database hemlock_test;'
  - source ./scripts/ci/setup_env_hemlock.sh
  - sudo service mongodb restart
  - sudo apt-get update -qq
  # - sudo apt-get install -y libssl0.9.8
  # - sudo wget http://packages.couchbase.com/releases/2.0.0/couchbase-server-enterprise_x86_64_2.0.0.deb
  # - sudo dpkg -i couchbase-server-enterprise_x86_64_2.0.0.deb
  # - sudo service couchbase-server start
  # - /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=Administrator --cluster-init-password=password --cluster-init-ramsize=256
  # - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=hemlock --bucket-password=password --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=100 --bucket-replica=0 -u Administrator -p password
install:
  - pip install APScheduler --use-mirrors
  - pip install MySQL-python --use-mirrors
  - pip install texttable --use-mirrors
  - pip install couchbase --use-mirrors
  - pip install pytest --use-mirrors
  - pip install pytest-cov --use-mirrors
  - pip install python-coveralls --use-mirrors
  - pip install pdfminer==20131113 --use-mirrors
  - pip install python-magic --use-mirrors
  - pip install xlrd --use-mirrors
  - pip install xmltodict --use-mirrors
  - pip install pymongo --use-mirrors
  - pip install redis --use-mirrors
  - pip install web.py --use-mirrors
  - pip install pyes --use-mirrors
  - pip install hemlock --use-mirrors
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - py.test --cov=hemlock
script: py.test -v --cov hemlock --cov-report term-missing
after_success:
  - coveralls
branches:
  except:
  - gh-pages
notifications:
  email:
    - charliel@lab41.org
