language: python
python:
  - "2.7"
before_install:
  - mysql -e 'create database hemlock_test;'
  - source ./scripts/ci/setup_env.sh
  - sudo apt-get update -qq
install: 
  - pip install MySQL-python --use-mirrors
  - pip install texttable --use-mirrors
  - pip install couchbase --use-mirrors
script: pytest
branches:
  except:
  - gh-pages
notifications:
  email:
    - charliel@lab41.org
