language: python
python:
  - "2.7"
before_install:
  - mysql -e 'create database hemlock_test;'
  - source ./scripts/ci/setup_env_hemlock.sh
  - sudo apt-get update -qq
  # - sudo apt-get install -y libssl0.9.8
  # - sudo wget http://packages.couchbase.com/releases/2.0.0/couchbase-server-enterprise_x86_64_2.0.0.deb
  # - sudo dpkg -i couchbase-server-enterprise_x86_64_2.0.0.deb
  # - sudo service couchbase-server start
  # - /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=Administrator --cluster-init-password=password --cluster-init-ramsize=256
  # - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=hemlock --bucket-password=password --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=100 --bucket-replica=0 -u Administrator -p password
install: 
  - pip install MySQL-python --use-mirrors
  - pip install texttable --use-mirrors
  - pip install couchbase --use-mirrors
  - pip install pytest --use-mirrors
script: py.test
branches:
  except:
  - gh-pages
notifications:
  email:
    - charliel@lab41.org
